// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package bridge

import (
	"github.com/google/uuid"
)

type Task struct {
	ID          uuid.UUID
	Title       string
	Description string
	Completed   bool
	CreatedAt   interface{}
	UpdatedAt   interface{}
}
