version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: task-manager-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: deveduardomelo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - db

  app:
    image: task-manager
    ports:
      - 9090:9090
    depends_on:
      - pgadmin
